// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcache

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockCache
func (_mock *MockCache) Exists(ctx context.Context, keys ...string) (int, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (int, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) int); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCache_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockCache_Expecter) Exists(ctx interface{}, keys ...interface{}) *MockCache_Exists_Call {
	return &MockCache_Exists_Call{Call: _e.mock.On("Exists",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockCache_Exists_Call) Run(run func(ctx context.Context, keys ...string)) *MockCache_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCache_Exists_Call) Return(n int, err error) *MockCache_Exists_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCache_Exists_Call) RunAndReturn(run func(ctx context.Context, keys ...string) (int, error)) *MockCache_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockCache
func (_mock *MockCache) GetString(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockCache_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) GetString(ctx interface{}, key interface{}) *MockCache_GetString_Call {
	return &MockCache_GetString_Call{Call: _e.mock.On("GetString", ctx, key)}
}

func (_c *MockCache_GetString_Call) Run(run func(ctx context.Context, key string)) *MockCache_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetString_Call) Return(s string, err error) *MockCache_GetString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCache_GetString_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockCache_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// Raw provides a mock function for the type MockCache
func (_mock *MockCache) Raw() *redis.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Raw")
	}

	var r0 *redis.Client
	if returnFunc, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}
	return r0
}

// MockCache_Raw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Raw'
type MockCache_Raw_Call struct {
	*mock.Call
}

// Raw is a helper method to define mock.On call
func (_e *MockCache_Expecter) Raw() *MockCache_Raw_Call {
	return &MockCache_Raw_Call{Call: _e.mock.On("Raw")}
}

func (_c *MockCache_Raw_Call) Run(run func()) *MockCache_Raw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Raw_Call) Return(client *redis.Client) *MockCache_Raw_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockCache_Raw_Call) RunAndReturn(run func() *redis.Client) *MockCache_Raw_Call {
	_c.Call.Return(run)
	return _c
}

// SetJSON provides a mock function for the type MockCache
func (_mock *MockCache) SetJSON(ctx context.Context, key string, value any, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJSON'
type MockCache_SetJSON_Call struct {
	*mock.Call
}

// SetJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetJSON(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockCache_SetJSON_Call {
	return &MockCache_SetJSON_Call{Call: _e.mock.On("SetJSON", ctx, key, value, ttl)}
}

func (_c *MockCache_SetJSON_Call) Run(run func(ctx context.Context, key string, value any, ttl time.Duration)) *MockCache_SetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_SetJSON_Call) Return(err error) *MockCache_SetJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetJSON_Call) RunAndReturn(run func(ctx context.Context, key string, value any, ttl time.Duration) error) *MockCache_SetJSON_Call {
	_c.Call.Return(run)
	return _c
}
