version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
    - gci
  settings:
    goimports:
      local-prefixes:
        - github.com/dev2choiz/api-skeleton
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/dev2choiz/api-skeleton)
linters:
  default: standard
  enable:
    - misspell
    # - perfsprint
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1000"
  exclusions:
    paths:
      - mocks
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
