services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "${PPROF_PORT}:${PPROF_PORT}"
      - "${API_PORT}:${API_PORT}"
      - "2345:2345"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:8
    ports:
      - "9379:6379"

  # Test environment
  api_test:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env.test
    depends_on:
      - postgres_test

  postgres_test:
    image: postgres:18
    ports:
      - "9433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: test

volumes:
  go-mod-cache:
