// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockrepository

import (
	"context"

	"github.com/dev2choiz/api-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetOneUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOneUser(ctx context.Context, filters entity.UserFilters) (entity.User, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetOneUser")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) (entity.User, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) entity.User); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UserFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOneUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneUser'
type MockRepository_GetOneUser_Call struct {
	*mock.Call
}

// GetOneUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filters entity.UserFilters
func (_e *MockRepository_Expecter) GetOneUser(ctx interface{}, filters interface{}) *MockRepository_GetOneUser_Call {
	return &MockRepository_GetOneUser_Call{Call: _e.mock.On("GetOneUser", ctx, filters)}
}

func (_c *MockRepository_GetOneUser_Call) Run(run func(ctx context.Context, filters entity.UserFilters)) *MockRepository_GetOneUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UserFilters
		if args[1] != nil {
			arg1 = args[1].(entity.UserFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOneUser_Call) Return(user entity.User, err error) *MockRepository_GetOneUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetOneUser_Call) RunAndReturn(run func(ctx context.Context, filters entity.UserFilters) (entity.User, error)) *MockRepository_GetOneUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUser(ctx context.Context, id string) (entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetUser(ctx interface{}, id interface{}) *MockRepository_GetUser_Call {
	return &MockRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockRepository_GetUser_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUser_Call) Return(user entity.User, err error) *MockRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (entity.User, error)) *MockRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUsers(ctx context.Context, filters entity.UserFilters) ([]entity.User, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) ([]entity.User, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) []entity.User); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UserFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters entity.UserFilters
func (_e *MockRepository_Expecter) GetUsers(ctx interface{}, filters interface{}) *MockRepository_GetUsers_Call {
	return &MockRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filters)}
}

func (_c *MockRepository_GetUsers_Call) Run(run func(ctx context.Context, filters entity.UserFilters)) *MockRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UserFilters
		if args[1] != nil {
			arg1 = args[1].(entity.UserFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUsers_Call) Return(users []entity.User, err error) *MockRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, filters entity.UserFilters) ([]entity.User, error)) *MockRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertUser(ctx context.Context, user entity.User) (entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) (entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *MockRepository_Expecter) InsertUser(ctx interface{}, user interface{}) *MockRepository_InsertUser_Call {
	return &MockRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user)}
}

func (_c *MockRepository_InsertUser_Call) Run(run func(ctx context.Context, user entity.User)) *MockRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.User
		if args[1] != nil {
			arg1 = args[1].(entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertUser_Call) Return(user1 entity.User, err error) *MockRepository_InsertUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_InsertUser_Call) RunAndReturn(run func(ctx context.Context, user entity.User) (entity.User, error)) *MockRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}
