// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockbusiness

import (
	"context"
	"net/http"

	"github.com/dev2choiz/api-skeleton/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBusiness creates a new instance of MockBusiness. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBusiness(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBusiness {
	mock := &MockBusiness{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBusiness is an autogenerated mock type for the Business type
type MockBusiness struct {
	mock.Mock
}

type MockBusiness_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBusiness) EXPECT() *MockBusiness_Expecter {
	return &MockBusiness_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockBusiness
func (_mock *MockBusiness) Authenticate(ctx context.Context, username string, password string) (string, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBusiness_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockBusiness_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockBusiness_Expecter) Authenticate(ctx interface{}, username interface{}, password interface{}) *MockBusiness_Authenticate_Call {
	return &MockBusiness_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, username, password)}
}

func (_c *MockBusiness_Authenticate_Call) Run(run func(ctx context.Context, username string, password string)) *MockBusiness_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBusiness_Authenticate_Call) Return(s string, err error) *MockBusiness_Authenticate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBusiness_Authenticate_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, error)) *MockBusiness_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockBusiness
func (_mock *MockBusiness) GetUsers(ctx context.Context, filters entity.UserFilters) ([]entity.User, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) ([]entity.User, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.UserFilters) []entity.User); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.UserFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBusiness_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockBusiness_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters entity.UserFilters
func (_e *MockBusiness_Expecter) GetUsers(ctx interface{}, filters interface{}) *MockBusiness_GetUsers_Call {
	return &MockBusiness_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, filters)}
}

func (_c *MockBusiness_GetUsers_Call) Run(run func(ctx context.Context, filters entity.UserFilters)) *MockBusiness_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.UserFilters
		if args[1] != nil {
			arg1 = args[1].(entity.UserFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBusiness_GetUsers_Call) Return(users []entity.User, err error) *MockBusiness_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockBusiness_GetUsers_Call) RunAndReturn(run func(ctx context.Context, filters entity.UserFilters) ([]entity.User, error)) *MockBusiness_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockBusiness
func (_mock *MockBusiness) Register(ctx context.Context, username string, password string) (entity.User, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (entity.User, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) entity.User); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBusiness_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockBusiness_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockBusiness_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *MockBusiness_Register_Call {
	return &MockBusiness_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *MockBusiness_Register_Call) Run(run func(ctx context.Context, username string, password string)) *MockBusiness_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBusiness_Register_Call) Return(user entity.User, err error) *MockBusiness_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockBusiness_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (entity.User, error)) *MockBusiness_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockBusiness
func (_mock *MockBusiness) ValidateToken(r *http.Request) (entity.User, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (entity.User, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) entity.User); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBusiness_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockBusiness_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockBusiness_Expecter) ValidateToken(r interface{}) *MockBusiness_ValidateToken_Call {
	return &MockBusiness_ValidateToken_Call{Call: _e.mock.On("ValidateToken", r)}
}

func (_c *MockBusiness_ValidateToken_Call) Run(run func(r *http.Request)) *MockBusiness_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBusiness_ValidateToken_Call) Return(user entity.User, err error) *MockBusiness_ValidateToken_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockBusiness_ValidateToken_Call) RunAndReturn(run func(r *http.Request) (entity.User, error)) *MockBusiness_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
